### PR TITLE
Global compression handlers

### PR DESCRIPTION
**Pull request by lmangani**
Testing @fastify/compress global compression/decompression handlers
Potential fix for https://github.com/metrico/qryn/issues/239

### CODE REVIEW

**Comment by akvlad** [comment]
@lmangani @Dletta 
- clickhouse log -> qryn
- clickhouse traces -> qryn
these can be affected by regressions. Please recheck in your test labs

**Review by akvlad — APPROVED** [review]

**Comment by lmangani** [comment]
@Dletta could you validate the MVs still work with this PR?

**Comment by Dletta** [comment]
Confirmed MV's still work. Sending some gzipped data.

**Comment by Dletta** [comment]
Confirmed it successfully unzips insert data.

**Comment by Dletta** [comment]
On read requests as below:
```javascript
var result = await axios.get('http://qryn.ip:3100/loki/api/v1/query_range?direction=backward&end=1671132590580000000&limit=1000&query=%7Blevel%3D%22Warning%22%7D&start=1671128990580000000&step=10000ms', {
    headers: {
      'Accept-Encoding': 'gzip'
    }
  })
  .catch((e)=> {
    console.log('error in get requests gzip:', e)
  })
  console.log('AXIOS gzip read', result.headers, result.status, result.statusText)
```

gzip is not returned to client asking for it.

**Pull request merged**
