### PR TITLE
Influx line protocol /write API

### PR DESCRIPTION
**Pull request by lmangani**
## Influx lineprotocol /write API
This PR implements an API set to handle Influx line protocol inserts into generic `unwrap_value` metric in qryn

#### Endpoints
* `/influx/api/v2/write` _accepts single line protocol inserts via `POST`

##### CURL
```
curl -i -XPOST 'http://localhost:3100/influx/api/v2/write' \
  --data-raw 'cpu_load_short,host=server01,region=us-west value=0.64 1434055562000000000'
```
```
curl -i -XPOST 'http://localhost:3100/influx/api/v2/write' \
  --data-raw 'syslog,appname=myapp,facility=console,host=myhost,hostname=myhost,severity=warning facility_code=14i,message="warning message here",severity_code=4i,procid="12345",timestamp=1434055562000000000,version=1'
```
##### ClickHouse MV _(working sketch)_
```
CREATE MATERIALIZED VIEW default.influx_log_send
ENGINE = URL('http://localhost:3100/influx/api/v2/write', 'LineAsString')
AS SELECT format('syslog,level={0},logger_name={1} message="{2}" {3}', 
  toString(level), 
  replaceRegexpAll(toString(logger_name), '[^a-zA-Z0-9_]', '_'), 
  replaceAll(replaceRegexpAll(message, '["\\\\]', '\x00\\0'), '\x00', '\\'), 
  toString(toUnixTimestamp64Nano(event_time_microseconds))) FROM system.text_log;
```

### CODE REVIEW

**Comment by lmangani** [comment]
Docs for review 
- https://qryn.metrico.in/#/metrics/ingestion?id=influx
- https://qryn.metrico.in/#/logs/ingestion?id=influx

**Comment by Dletta** [comment]
I setup test lab for this branch and then curl'd according to docs, which returns Code 500.

```bash
14|dev-influx  | {"level":50,"time":1660682265121,"pid":18604,"hostname":"de5","name":"qryn","reqId":"req-2","msg":"POST INFLUX /write"}
14|dev-influx  | {"level":50,"time":1660682265122,"pid":18604,"hostname":"de5","name":"qryn","reqId":"req-2","err":"this.fingerPrint is not a function\nTypeError: this.fingerPrint is not a function\n    at /usr/src/cloki-dev/lib/handlers/influx_write.js:79:23\n    at Array.forEach (<anonymous>)\n    at Object.handler (/usr/src/cloki-dev/lib/handlers/influx_write.js:61:13)\n    at Object.routeOptions.handler (/usr/src/cloki-dev/node_modules/fastify-websocket/index.js:130:24)\n    at preHandlerCallback (/usr/src/cloki-dev/node_modules/fastify/lib/handleRequest.js:126:28)\n    at preValidationCallback (/usr/src/cloki-dev/node_modules/fastify/lib/handleRequest.js:109:5)\n    at handler (/usr/src/cloki-dev/node_modules/fastify/lib/handleRequest.js:72:7)\n    at done (/usr/src/cloki-dev/node_modules/fastify/lib/contentTypeParser.js:170:7)\n    at /usr/src/cloki-dev/node_modules/fastify/lib/contentTypeParser.js:161:27\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","msg":"this.fingerPrint is not a function"}
14|dev-influx  | {"level":50,"time":1660682265122,"pid":18604,"hostname":"de5","name":"qryn","reqId":"req-2","err":"Cannot read property 'add' of undefined\nTypeError: Cannot read property 'add' of undefined\n    at /usr/src/cloki-dev/lib/handlers/influx_write.js:115:21\n    at Array.forEach (<anonymous>)\n    at Object.handler (/usr/src/cloki-dev/lib/handlers/influx_write.js:61:13)\n    at Object.routeOptions.handler (/usr/src/cloki-dev/node_modules/fastify-websocket/index.js:130:24)\n    at preHandlerCallback (/usr/src/cloki-dev/node_modules/fastify/lib/handleRequest.js:126:28)\n    at preValidationCallback (/usr/src/cloki-dev/node_modules/fastify/lib/handleRequest.js:109:5)\n    at handler (/usr/src/cloki-dev/node_modules/fastify/lib/handleRequest.js:72:7)\n    at done (/usr/src/cloki-dev/node_modules/fastify/lib/contentTypeParser.js:170:7)\n    at /usr/src/cloki-dev/node_modules/fastify/lib/contentTypeParser.js:161:27\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","msg":"Cannot read property 'add' of undefined"}
14|dev-influx  | {"level":30,"time":1660682265123,"pid":18604,"hostname":"de5","name":"qryn","reqId":"req-2","res":{"statusCode":500},"responseTime":4.271903991699219,"msg":"request completed"}
```

the command used was from documentation

```
dletta@Jachens-MBP ~ % curl -i -XPOST 'http://dev-influx:3104/write' \
  --data-raw 'cpu_load_short,host=server01,region=us-west value=0.64 1660683366000000000'
HTTP/1.1 500 Internal Server Error
vary: Origin
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 84
Date: Tue, 16 Aug 2022 20:56:34 GMT
Connection: keep-alive
Keep-Alive: timeout=5

{"statusCode":500,"error":"Internal Server Error","message":"Internal Server Error"}%

**Comment by akvlad** [comment]
pushed some debug please recheck

**Comment by lmangani** [comment]
> this.fingerPrint is not a function

It's probably just missing a `.bind(this)` in a spawned function scope?

**Comment by Dletta** [comment]
Tested and approved

**Pull request merged**
