### PR TITLE
fix: span attributes maybe is null

### PR DESCRIPTION
**Pull request by Cluas**
@lmangani @akvlad PTAL

### CODE REVIEW

**Comment by Cluas** [comment]
should be fix https://github.com/metrico/qryn/issues/259

**Comment by akvlad** [comment]
Thanks a lot. I'll check against e2e and merge to the beta branch.

**Comment by lmangani** [comment]
Thanks for the self-fix and welcome to our tiny contributors list! This is very much appreciated! @Cluas 👍

**Comment by Cluas** [comment]
😂 If this project was written by go, I'd probably be contributing code like crazy and learning a lot from it. About the design of the clickhouse schema and such. Thanks for the open source.

**Comment by akvlad** [comment]
If no objections, merging to the beta for the further testing.

**Comment by lmangani** [comment]
> 😂 If this project was written by go, I'd probably be contributing code like crazy and learning a lot from it

There is a go version and we're looking for developers. Message info@qryn.dev if interested 😉

**Comment by Cluas** [comment]
@akvlad Does the beta branch package docker images now?

**Comment by Cluas** [comment]
> > 😂 If this project was written by go, I'd probably be contributing code like crazy and learning a lot from it
> 
> There is a go version and we're looking for developers. Message [info@qryn.dev](mailto:info@qryn.dev) if interested 😉

I do have an interest.

**Pull request merged**
