### PR TITLE
/series request optimizations

### PR DESCRIPTION
**Pull request by akvlad**
use pako for gzip; ADVANCED_SERIES_REQUEST_LIMIT to limit /series response

### CODE REVIEW

**Comment by humphd** [comment]
@akvlad we started seeing crashes when we updated to this change (v3.2.30) in our cluster:

```
/app/node_modules/stream-shift/index.js:16
    return state.buffer[0].length
                           ^

TypeError: Cannot read properties of null (reading 'length')
    at getStateLength (/app/node_modules/stream-shift/index.js:16:28)
    at shift (/app/node_modules/stream-shift/index.js:6:99)
    at Duplexify._forward (/app/node_modules/peek-stream/node_modules/duplexify/index.js:168:35)
    at Duplex.onreadable (/app/node_modules/peek-stream/node_modules/duplexify/index.js:134:10)
    at Duplex.emit (node:events:519:28)
    at emitReadable_ (node:internal/streams/readable:832:12)
    at onEofChunk (node:internal/streams/readable:810:5)
    at readableAddChunkPushByteMode (node:internal/streams/readable:464:5)
    at Readable.push (node:internal/streams/readable:390:5)
    at deflator.onEnd (/app/qryn_node.js:142:19)
```

Not sure if it's our bug (missing some new config) or something for you to know about.

**Comment by akvlad** [comment]
@humphd thanks for the report. Will fix.

**Comment by akvlad** [comment]
@humphd apparently a node version problem. Very strange. please try 3.2.31.

Sorry for the inconvenience.

**Comment by humphd** [comment]
> @humphd apparently a node version problem. Very strange. please try 3.2.31.
> 
> Sorry for the inconvenience.

Amazing, thank you! We'll try.

**Pull request merged**
