### PR TITLE
Promql to LogQL emulation

### PR DESCRIPTION
**Pull request by lmangani**
## PromQL Emulation APIs
This PR implements an API set to handle and transpile simple PromQL queries into LogQL `unwrap_value` metric in qryn

#### About
The [WASM parser](https://github.com/lmangani/rust-promql-parser-js) and [sqrl transpiler](https://github.com/lmangani/promql2logql) templates only support extremely basic queries, ie:
* Input: ```rate(foo{"bar"="baz")[5m]) by (x,y)```
* Output: ```rate({"__name__"="foo", "bar"="baz"} | unwrap_value [300s]) by (x,y)```

##### Endpoints
- [x] `fastify.get('/api/v1/query_range', handlerPromQueryRange)`
- [x] `fastify.get('/api/v1/query', handlerPromQuery)`
- [x] `fastify.get('/api/v1/labels', handlerPromLabel) // piggyback on qryn labels`
- [x] `fastify.get('/api/v1/label/:name/values', handlerPromLabelValues) // piggyback on qryn values`
- [x] `fastify.post('/api/v1/labels', handlerPromLabel) // piggyback on qryn labels`
- [x] `fastify.post('/api/v1/label/:name/values', handlerPromLabelValues) // piggyback on qryn values`
- [x] `fastify.get('/api/v1/metadata', handlerPromDefault) // default handler TBD`
- [x] `fastify.get('/api/v1/rules', handlerPromDefault) // default handler TBD`
- [x] `fastify.get('/api/v1/query_exemplars', handlerPromDefault) // default handler TBD`
- [x] `fastify.get('/api/v1/status/buildinfo', handlerPromDefault) // default handler TBD`

#### Issues
- [x] Adjust start/stop timestamp format to match LogQL API requirements
- [x] Adjust response format to match PromQL requirements

#### References
* [Prometheus querying API](https://prometheus.io/docs/prometheus/latest/querying/api/)
* [promql2logql](https://github.com/lmangani/promql2logql)
* [promql-parser-js](https://github.com/lmangani/rust-promql-parser-js)

### CODE REVIEW

**Comment by lmangani** [comment]
Temporarily bypassed time boundaries on Prometheus label and label/values lookups:
image

**Comment by lmangani** [comment]
Ready for some testing @Dletta :

**Comment by Dletta** [comment]
Support for following PromQL queries:

- [X] ```{tag="name"}```
- [X] ```label {}```
- [X] ```rate(label [interval])```
- [X] ```sum(rate(label [interval]))```

**Comment by lmangani** [comment]
TODO: Extend Prometheus Wiki page + list known limitations

**Pull request merged**
